[master]
192.168.1.101

[nodes]
192.168.1.102
192.168.1.103
192.168.1.104

[cluster:children]
master
nodes

[cluster:vars]
ansible_become_pass=atomic
ansible_ssh_user=atomic
ansible_ssh_pass=atomic
ansible_become=yes
